CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE organizations (id uuid PRIMARY KEY, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY, email text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organization_members (organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id), role text NOT NULL, PRIMARY KEY (organization_id, user_id));
CREATE TABLE drone_models (id uuid PRIMARY KEY, manufacturer text NOT NULL, name text NOT NULL, max_payload_grams integer NOT NULL CHECK (max_payload_grams >= 0));
CREATE TABLE drones (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), model_id uuid REFERENCES drone_models(id), status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE batteries (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), drone_id uuid REFERENCES drones(id), cycle_count integer NOT NULL DEFAULT 0 CHECK (cycle_count >= 0));
CREATE TABLE orders (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE packages (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), order_id uuid NOT NULL REFERENCES orders(id), weight_grams integer NOT NULL CHECK (weight_grams >= 0));
CREATE TABLE missions (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), drone_id uuid REFERENCES drones(id), order_id uuid REFERENCES orders(id), status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE mission_waypoints (id uuid PRIMARY KEY, mission_id uuid NOT NULL REFERENCES missions(id), sequence integer NOT NULL, position geometry(PointZ, 4326) NOT NULL, UNIQUE (mission_id, sequence));
CREATE TABLE recipients (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), order_id uuid NOT NULL REFERENCES orders(id));
CREATE TABLE deliveries (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), mission_id uuid REFERENCES missions(id), recipient_id uuid REFERENCES recipients(id), status text NOT NULL);
CREATE TABLE telemetry_metadata (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), drone_id uuid NOT NULL REFERENCES drones(id), observed_at timestamptz NOT NULL, source text NOT NULL);
CREATE TABLE geofences (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, boundary geometry(Polygon, 4326) NOT NULL);
CREATE TABLE weather_snapshots (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), observed_at timestamptz NOT NULL, payload jsonb NOT NULL);
CREATE TABLE alerts (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), mission_id uuid REFERENCES missions(id), severity text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE incidents (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), mission_id uuid REFERENCES missions(id), status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notifications (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid REFERENCES users(id), type text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_logs (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), actor_user_id uuid REFERENCES users(id), action text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
