import { Product } from '../types/product';
import { CustomerAddress } from '../types/address';
import { CustomerOrder } from '../types/order';
import { CustomerNotification } from '../types/notification';
import { FAQItem, SupportTicket } from '../types/support';
import { CustomerUser } from '../types/auth';

export const INITIAL_USER: CustomerUser = {
  id: 'cust_984210',
  name: 'Alex Mercer',
  email: 'alex.mercer@skylink.io',
  phone: '+1 (555) 248-7790',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  isVerified: true,
  accountStatus: 'active',
  createdAt: '2026-01-15T09:30:00.000Z',
  updatedAt: '2026-08-20T14:22:00.000Z',
  notificationPreferences: {
    emailUpdates: true,
    smsAlerts: true,
    droneProximitySound: true,
  },
};

export const INITIAL_ADDRESSES: CustomerAddress[] = [
  {
    id: 'addr_1',
    customerId: 'cust_984210',
    label: 'Home',
    name: 'Alex Mercer',
    phone: '+1 (555) 248-7790',
    building: 'Apt 4B, Apex Heights',
    street: '742 Evergreen Terrace',
    area: 'Skyline District',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94107',
    latitude: 37.7749,
    longitude: -122.4194,
    instructions: 'Lower package onto the marked AstroTurf pad in backyard lawn. Call if wind is high.',
    isDefault: true,
    dropZoneType: 'Lawn',
  },
  {
    id: 'addr_2',
    customerId: 'cust_984210',
    label: 'Office',
    name: 'Alex Mercer (Work)',
    phone: '+1 (555) 248-7790',
    building: 'Horizon Tower 3, Floor 14',
    street: '500 Howard Street',
    area: 'SoMa Tech Corridor',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94105',
    latitude: 37.7885,
    longitude: -122.3972,
    instructions: 'Designated rooftop drone landing beacon #2. Reception security will notify upon ping.',
    isDefault: false,
    dropZoneType: 'Rooftop Pad',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Medicine & Urgent Health
  {
    id: 'prod_med_1',
    name: 'AeroFirst Rapid First Aid & Trauma Burn Kit',
    brand: 'AeroHealth Labs',
    category: 'Medicine',
    subCategory: 'First Aid',
    description: 'Hospital-grade emergency trauma pack certified for rapid aerial dispatch. Includes sterile burn dressings, hemostatic gauze, sutures, and antiseptic spray.',
    price: 499,
    originalPrice: 799,
    discountPercent: 38,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 0.8,
    estimatedDeliveryMins: 9,
    inStock: true,
    stockCount: 25,
    badge: 'Critical Priority Drone',
    features: ['Sterile packaging certified', 'Emergency rapid response pack', 'Waterproof Kevlar pouch'],
    specifications: {
      'Kit Contents': '64 Sterile Medical Pieces',
      'Certification': 'FDA Class II Approved',
      'Weight': '420 grams',
      'Container Type': 'Thermal Shock-Proof',
    },
    dimensions: '18 x 12 x 5 cm',
    weightGrams: 420,
    customerReviews: [
      {
        id: 'rev_1',
        author: 'Dr. Sarah Lin',
        rating: 5,
        date: 'August 18, 2026',
        title: 'Landed in my backyard in 8 mins during an emergency!',
        comment: 'Needed sterile gauze and burn dressing immediately. The drone hovered perfectly and lowered the kit gently.',
        verifiedPurchase: true,
        helpfulCount: 42,
      },
      {
        id: 'rev_2',
        author: 'Mark Davis',
        rating: 5,
        date: 'August 12, 2026',
        title: 'Highest quality first aid kit',
        comment: 'Every item is sealed individually. Great peace of mind having this delivered so quickly.',
        verifiedPurchase: true,
        helpfulCount: 19,
      },
    ],
  },
  {
    id: 'prod_med_2',
    name: 'Glucofast Instant Glucose Monitor & 50 Test Strips',
    brand: 'BioMetrics Health',
    category: 'Medicine',
    subCategory: 'Medical Devices',
    description: 'High-precision blood glucose monitoring device with wireless Bluetooth sync and 50 pre-calibrated test strips. Pre-packaged for air transit.',
    price: 1299,
    originalPrice: 1999,
    discountPercent: 35,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 96,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 0.5,
    estimatedDeliveryMins: 11,
    inStock: true,
    stockCount: 18,
    badge: 'Express Medical',
    features: ['Instant results in 5s', 'Bluetooth mobile app sync', '50 sterile strips included'],
    specifications: {
      'Sample Size': '0.5 µL Blood',
      'Battery Life': '1,000 Tests',
      'Weight': '210 grams',
      'Memory': '500 Historical Readings',
    },
    dimensions: '10 x 6 x 3 cm',
    weightGrams: 210,
  },
  {
    id: 'prod_med_3',
    name: 'BioShield Rapid Antihistamine & Allergy Relief (30 Caps)',
    brand: 'PharmaShield',
    category: 'Medicine',
    subCategory: 'Allergy Care',
    description: 'Non-drowsy 24h fast relief tablets for acute seasonal pollen, dust, and contact allergic reactions.',
    price: 199,
    originalPrice: 260,
    discountPercent: 23,
    currency: 'INR',
    rating: 4.7,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 0.2,
    estimatedDeliveryMins: 10,
    inStock: true,
    stockCount: 40,
    badge: 'Urgent Care',
    features: ['24-hour non-drowsy relief', 'Fast absorption within 15 min', 'Child-safe lock cap'],
    specifications: {
      'Active Ingredient': 'Cetirizine HCl 10mg',
      'Count': '30 Softgels',
      'Weight': '95 grams',
    },
    dimensions: '8 x 4 x 4 cm',
    weightGrams: 95,
  },

  // Gourmet Food & Meals
  {
    id: 'prod_food_1',
    name: 'Artisan Woodfired Truffle Mushroom Pizza (12")',
    brand: 'La Stella Cucina',
    category: 'Food',
    subCategory: 'Gourmet Meals',
    description: 'Hand-stretched sourdough pizza with Italian black truffles, wild mushrooms, and buffalo mozzarella. Transported at 68°C in a thermal insulated drone pod.',
    price: 599,
    originalPrice: 799,
    discountPercent: 25,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 310,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 1.2,
    estimatedDeliveryMins: 14,
    inStock: true,
    stockCount: 15,
    badge: 'Hot In-Flight Container 68°C',
    features: ['Thermo-locking sealed box', 'Fresh Italian black truffle', 'Arrives piping hot'],
    specifications: {
      'Size': '12 Inch Artisan Pie',
      'Serving': '2-3 Persons',
      'Transit Container': 'Active Thermal Heated 68°C',
      'Weight': '750 grams',
    },
    dimensions: '30 x 30 x 4 cm',
    weightGrams: 750,
    customerReviews: [
      {
        id: 'rev_3',
        author: 'Elena Rostova',
        rating: 5,
        date: 'August 24, 2026',
        title: 'Still steaming hot when the drone lowered it!',
        comment: 'Unbelievable experience. The pizza crust was crispy and the cheese was perfectly melted. Arrived in 13 minutes.',
        verifiedPurchase: true,
        helpfulCount: 56,
      },
    ],
  },
  {
    id: 'prod_food_2',
    name: 'Kyoto Special Wild Salmon Sashimi & Nigiri Bento',
    brand: 'Sushi Zen Kyoto',
    category: 'Food',
    subCategory: 'Japanese Cuisine',
    description: 'Chef selection of Norwegian wild salmon sashimi, hamachi nigiri, and bluefin tuna roll packed in a sub-zero dry ice cell capsule.',
    price: 649,
    originalPrice: 849,
    discountPercent: 24,
    currency: 'INR',
    rating: 4.95,
    reviewCount: 220,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 1.0,
    estimatedDeliveryMins: 12,
    inStock: true,
    stockCount: 12,
    badge: 'Chilled Temperature Pack',
    features: ['Sub-zero chilling pack', 'Fresh grated Shizuoka wasabi', 'Zero oxidation seal'],
    specifications: {
      'Pieces': '18 Premium Cuts',
      'Origin': 'Wild Caught Sustainable',
      'Transit Container': 'Ice-Lock Sub-Zero Capsule',
      'Weight': '580 grams',
    },
    dimensions: '22 x 16 x 6 cm',
    weightGrams: 580,
  },
  {
    id: 'prod_food_3',
    name: 'Gourmet Double Smash Cheeseburger & Rosemary Truffle Fries',
    brand: 'Burger Foundry',
    category: 'Food',
    subCategory: 'Burgers',
    description: 'Prime Angus beef double patties, aged smoked gouda, caramelized shallots, house secret sauce, and crisp rosemary truffle fries.',
    price: 389,
    originalPrice: 499,
    discountPercent: 22,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 405,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 0.9,
    estimatedDeliveryMins: 13,
    inStock: true,
    stockCount: 30,
    badge: 'Bestseller Food',
    features: ['Crisp-lock steam release box', 'Double 100% Angus beef', 'Toasted brioche bun'],
    specifications: {
      'Meat': '100% Angus Beef (Quarter Pound x2)',
      'Side': 'Rosemary Sea Salt Truffle Fries',
      'Weight': '620 grams',
    },
    dimensions: '20 x 15 x 10 cm',
    weightGrams: 620,
  },

  // Fresh Groceries & Essentials
  {
    id: 'prod_groc_1',
    name: 'Organic Hass Avocados & Golden Berries Bundle',
    brand: 'SkyFarm Organics',
    category: 'Groceries',
    subCategory: 'Fresh Produce',
    description: 'Hand-picked ripe Hass avocados (4x) and fresh sweet golden berries (250g) harvested this morning.',
    price: 349,
    originalPrice: 450,
    discountPercent: 22,
    currency: 'INR',
    rating: 4.6,
    reviewCount: 75,
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 1.1,
    estimatedDeliveryMins: 15,
    inStock: true,
    stockCount: 20,
    badge: 'Farm Direct Today',
    features: ['Plucked within last 6 hours', 'Certified USDA organic', 'Zero bruising transit guarantee'],
    specifications: {
      'Origin': 'SkyFarm California Orchards',
      'Count': '4 Avocados + 250g Berries',
      'Weight': '850 grams',
    },
    dimensions: '24 x 18 x 8 cm',
    weightGrams: 850,
  },
  {
    id: 'prod_groc_2',
    name: 'Single-Origin Artisan Cold Brew Concentrate (1 Liter Glass)',
    brand: 'Altitude Roasters',
    category: 'Groceries',
    subCategory: 'Beverages',
    description: 'Ethiopian Yirgacheffe heirloom beans steeped for 24 hours in glacial water. Notes of blueberry, bergamot, and dark chocolate.',
    price: 13.99,
    originalPrice: 18.50,
    discountPercent: 24,
    rating: 4.85,
    reviewCount: 180,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 1.3,
    estimatedDeliveryMins: 12,
    inStock: true,
    stockCount: 22,
    badge: 'Morning Essential',
    features: ['Zero sugar or additives', 'Yields 8-10 servings', 'Shock-proof glass air holster'],
    specifications: {
      'Volume': '1,000 mL (33.8 fl oz)',
      'Roast Level': 'Medium Light',
      'Caffeine': '160mg per 150ml serving',
      'Weight': '1,100 grams',
    },
    dimensions: '9 x 9 x 24 cm',
    weightGrams: 1100,
  },

  // Electronics & Fast Tech
  {
    id: 'prod_elec_1',
    name: 'VoltWave 100W GaN Pro Fast Charger + 2m Braided Cable',
    brand: 'VoltWave Tech',
    category: 'Electronics',
    subCategory: 'Power & Cables',
    description: 'Pocket-sized Gallium Nitride 3-port charger (2x USB-C, 1x USB-A) capable of fast-charging laptops, tablets, and phones simultaneously.',
    price: 39.99,
    originalPrice: 59.99,
    discountPercent: 33,
    rating: 4.9,
    reviewCount: 260,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 0.4,
    estimatedDeliveryMins: 11,
    inStock: true,
    stockCount: 35,
    badge: 'Tech Deal of the Day',
    features: ['100W Max Power Delivery', 'Foldable US/EU prongs', 'Includes 100W 2m Cable'],
    specifications: {
      'Output': 'USB-C1 (100W), USB-C2 (65W), USB-A (22.5W)',
      'Technology': 'GaN III Semiconductor',
      'Weight': '230 grams',
      'Compatibility': 'MacBook Pro, iPhone, iPad, Galaxy, Dell XPS',
    },
    dimensions: '6 x 6 x 3 cm',
    weightGrams: 230,
    customerReviews: [
      {
        id: 'rev_4',
        author: 'Jason Vance',
        rating: 5,
        date: 'August 22, 2026',
        title: 'Emergency charger saved my Zoom presentation!',
        comment: 'My charger died 25 mins before an executive pitch. Ordered via SkyLink and the drone was at my office rooftop in 11 minutes.',
        verifiedPurchase: true,
        helpfulCount: 88,
      },
    ],
  },
  {
    id: 'prod_elec_2',
    name: 'AeroPods Spatial ANC Wireless Earbuds (36h Battery)',
    brand: 'AeroSound Labs',
    category: 'Electronics',
    subCategory: 'Audio',
    description: 'Next-gen active noise-canceling wireless earbuds with spatial head tracking, transparency mode, and IPX5 water resistance.',
    price: 89.99,
    originalPrice: 129.99,
    discountPercent: 31,
    rating: 4.8,
    reviewCount: 190,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 0.3,
    estimatedDeliveryMins: 12,
    inStock: true,
    stockCount: 14,
    badge: 'Premium Audio',
    features: ['42dB Active Noise Cancellation', 'Qi Wireless & USB-C charging', 'Dual beamforming mics'],
    specifications: {
      'Driver': '11mm Graphene Dynamic Drivers',
      'Battery Life': '8h Earbuds + 28h Case',
      'Bluetooth': 'Version 5.3 Low Latency',
      'Weight': '180 grams with case',
    },
    dimensions: '6 x 5 x 2.5 cm',
    weightGrams: 180,
  },

  // Documents & Security
  {
    id: 'prod_doc_1',
    name: 'AeroLock High-Security Tamper-Proof Legal Courier Pouch',
    brand: 'SkySecure Logistics',
    category: 'Documents',
    subCategory: 'Secure Courier',
    description: 'RFID-tracked, water-sealed, Kevlar reinforced courier pouch designed for urgent notarized contracts, passports, keys, and confidential papers.',
    price: 18.50,
    originalPrice: 24.00,
    discountPercent: 23,
    rating: 4.95,
    reviewCount: 84,
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 0.5,
    estimatedDeliveryMins: 8,
    inStock: true,
    stockCount: 50,
    badge: 'Lightning 8-Min Air Courier',
    features: ['One-time tamper seal with serial ID', 'Kevlar slash-resistant weave', 'End-to-end telemetry beacon'],
    specifications: {
      'Capacity': 'Up to 150 Sheets Letter/A4 Size',
      'Lock Mechanism': 'AeroLock Tamper Indicator',
      'Weight': '150 grams',
    },
    dimensions: '32 x 24 x 1 cm',
    weightGrams: 150,
  },

  // Daily Essentials & Pet
  {
    id: 'prod_oth_1',
    name: 'AeroPet VetCare Emergency Flea & Tick Treatment',
    brand: 'VetShield Health',
    category: 'Other',
    subCategory: 'Pet Care',
    description: 'Fast-acting topical treatment kills fleas and ticks within 4 hours. Waterproof and vet certified for dogs and cats.',
    price: 24.99,
    originalPrice: 32.00,
    discountPercent: 22,
    rating: 4.75,
    reviewCount: 62,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&auto=format&fit=crop&q=80',
    ],
    isDroneEligible: true,
    maxPayloadKg: 0.3,
    estimatedDeliveryMins: 10,
    inStock: true,
    stockCount: 16,
    badge: 'Pet Care Priority',
    features: ['Fast acting in 4 hours', 'Vet approved formula', '3-Month supply in box'],
    specifications: {
      'Target': 'Dogs & Cats (5-25 kg)',
      'Dosage': '3 Pipettes Included',
      'Weight': '120 grams',
    },
    dimensions: '12 x 8 x 3 cm',
    weightGrams: 120,
  },
];

export const INITIAL_ORDERS: CustomerOrder[] = [
  {
    id: 'ORD-10245',
    customerId: 'cust_984210',
    items: [
      { product: INITIAL_PRODUCTS[0], quantity: 1 }, // Medical kit
      { product: INITIAL_PRODUCTS[8], quantity: 1 }, // 100W GaN charger
    ],
    subtotal: 74.98,
    deliveryFee: 0, // Free drone express over $50
    tax: 6.37,
    discount: 5.00,
    total: 76.35,
    paymentMethod: 'Credit Card',
    paymentStatus: 'Paid',
    status: 'Out for Delivery',
    deliverySpeed: 'express',
    deliveryAddress: INITIAL_ADDRESSES[0],
    deliveryInstructions: 'Lower package onto the marked AstroTurf pad in backyard lawn.',
    dropZoneType: 'Lawn',
    deliveryOtp: '8492',
    isCancellable: false,
    estimatedDeliveryTime: '8 minutes',
    estimatedArrivalTimestamp: new Date(Date.now() + 8 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    timeline: [
      {
        status: 'Order Placed',
        timestamp: '11:15 AM',
        description: 'Customer order placed successfully and payment secured.',
        completed: true,
      },
      {
        status: 'Order Confirmed',
        timestamp: '11:16 AM',
        description: 'Order confirmed and inventory locked at SkyHub Central.',
        completed: true,
      },
      {
        status: 'Preparing',
        timestamp: '11:18 AM',
        description: 'Items loaded and balanced inside AeroSafe cargo compartment.',
        completed: true,
      },
      {
        status: 'Drone Assigned',
        timestamp: '11:21 AM',
        description: 'AeroSky Drone #04 assigned with verified airspace corridor.',
        completed: true,
      },
      {
        status: 'Drone Launched',
        timestamp: '11:23 AM',
        description: 'Drone departed launchpad and cruising at 65m altitude.',
        completed: true,
      },
      {
        status: 'Out for Delivery',
        timestamp: '11:25 AM',
        description: 'In-flight en route to destination landing coordinates.',
        completed: true,
      },
      {
        status: 'Near Destination',
        timestamp: 'Expected 11:31 AM',
        description: 'Drone enters terminal descent zone over customer coordinates.',
        completed: false,
      },
      {
        status: 'Arriving',
        timestamp: 'Expected 11:32 AM',
        description: 'Precision sonar alignment over landing pad.',
        completed: false,
      },
      {
        status: 'Delivered',
        timestamp: 'Expected 11:33 AM',
        description: 'Package safely released and customer OTP verified.',
        completed: false,
      },
    ],
  },
  {
    id: 'ORD-10190',
    customerId: 'cust_984210',
    items: [
      { product: INITIAL_PRODUCTS[3], quantity: 1 }, // Artisan Pizza
      { product: INITIAL_PRODUCTS[7], quantity: 1 }, // Cold Brew
    ],
    subtotal: 35.98,
    deliveryFee: 3.50,
    tax: 3.15,
    discount: 5.00,
    total: 37.63,
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    status: 'Delivered',
    deliverySpeed: 'standard',
    deliveryAddress: INITIAL_ADDRESSES[0],
    deliveryInstructions: 'Backyard lawn drop-off pad.',
    dropZoneType: 'Lawn',
    deliveryOtp: '4190',
    isCancellable: false,
    estimatedDeliveryTime: 'Delivered',
    createdAt: '2026-08-27T18:30:00.000Z',
    updatedAt: '2026-08-27T18:48:00.000Z',
    completedAt: '2026-08-27T18:48:00.000Z',
    rating: {
      stars: 5,
      feedback: 'The pizza was blazing hot and arrived in under 15 minutes! Super smooth drop.',
      submittedAt: '2026-08-27T19:00:00.000Z',
    },
    timeline: [
      { status: 'Order Placed', timestamp: '6:30 PM', description: 'Order received', completed: true },
      { status: 'Order Confirmed', timestamp: '6:31 PM', description: 'Order verified', completed: true },
      { status: 'Preparing', timestamp: '6:33 PM', description: 'Food packaged in thermal container', completed: true },
      { status: 'Drone Assigned', timestamp: '6:35 PM', description: 'AeroSky Drone #02 assigned', completed: true },
      { status: 'Drone Launched', timestamp: '6:37 PM', description: 'Drone launched', completed: true },
      { status: 'Out for Delivery', timestamp: '6:38 PM', description: 'En route', completed: true },
      { status: 'Near Destination', timestamp: '6:45 PM', description: 'Approaching landing coordinates', completed: true },
      { status: 'Arriving', timestamp: '6:47 PM', description: 'Descending to 2m drop height', completed: true },
      { status: 'Delivered', timestamp: '6:48 PM', description: 'Delivered smoothly onto AstroTurf pad', completed: true },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: CustomerNotification[] = [
  {
    id: 'notif_1',
    customerId: 'cust_984210',
    orderId: 'ORD-10245',
    title: 'Drone En Route! 🚀',
    message: 'Your delivery drone is cruising at safe altitude. Estimated arrival in 8 mins.',
    category: 'drone',
    read: false,
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    actionUrl: '/tracking/ORD-10245',
  },
  {
    id: 'notif_2',
    customerId: 'cust_984210',
    orderId: 'ORD-10245',
    title: 'Delivery OTP Ready',
    message: 'Your handover OTP is 8492. Keep it ready when the drone arrives.',
    category: 'security',
    read: false,
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    actionUrl: '/tracking/ORD-10245',
  },
  {
    id: 'notif_3',
    customerId: 'cust_984210',
    orderId: 'ORD-10190',
    title: 'Order Delivered 🎉',
    message: 'Order #ORD-10190 was delivered successfully. Tap to rate your flight experience.',
    category: 'order',
    read: true,
    createdAt: '2026-08-27T18:48:00.000Z',
    actionUrl: '/orders/ORD-10190',
  },
];

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: 'faq_1',
    category: 'Drone Delivery',
    question: 'How does drone delivery work?',
    answer: 'Once you place an order, our fulfillment hub packages your items in an aerodynamic thermal cargo container. An autonomous electric delivery drone is assigned, takes off along designated commercial air corridors at ~65m altitude, navigates to your GPS drop-off marker, gently lowers the package from 2 meters, and ascends back.',
  },
  {
    id: 'faq_2',
    category: 'Safety & Drop-off',
    question: 'Where can the drone land or drop my package?',
    answer: 'Drones require an unobstructed 2.5m x 2.5m clear area. Ideal drop zones include backyard lawns, driveways, flat rooftop landing pads, and designated apartment landing beacons. The area should be free of overhead powerlines and thick tree branches.',
  },
  {
    id: 'faq_3',
    category: 'Orders & Tracking',
    question: 'How does the Delivery OTP work?',
    answer: 'For secure handover, your tracking screen displays a 4-digit Delivery OTP. Once the drone arrives and enters hovering drop mode, confirm the OTP in your app to release the package tether safely.',
  },
  {
    id: 'faq_4',
    category: 'Safety & Drop-off',
    question: 'What happens in bad weather or strong winds?',
    answer: 'Our systems monitor hyper-local weather sensors in real-time. If wind speeds exceed safe operational limits or severe rain occurs, flights are automatically placed on temporary hold or rerouted. You will be notified immediately.',
  },
  {
    id: 'faq_5',
    category: 'Payments & Refunds',
    question: 'Can I cancel an order once placed?',
    answer: 'You can cancel your order free of charge at any time before the drone departs the launchpad (during Order Placed, Confirmed, or Preparing stages). Once the drone has launched into the flight corridor, cancellation is locked to ensure flight safety.',
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-8021',
    customerId: 'cust_984210',
    orderId: 'ORD-10190',
    category: 'General inquiry',
    subject: 'Rooftop landing beacon setup for office building',
    description: 'I would like to inquire about registering our office rooftop beacon ID for daily coffee deliveries.',
    status: 'Resolved',
    priority: 'Low',
    createdAt: '2026-08-25T14:10:00.000Z',
    updatedAt: '2026-08-26T09:20:00.000Z',
    messages: [
      {
        id: 'msg_1',
        sender: 'customer',
        senderName: 'Alex Mercer',
        message: 'I would like to inquire about registering our office rooftop beacon ID for daily coffee deliveries.',
        timestamp: '2026-08-25T14:10:00.000Z',
      },
      {
        id: 'msg_2',
        sender: 'support',
        senderName: 'SkyLink Support Team',
        message: 'Hi Alex! Your office address Horizon Tower 3 is already linked to Rooftop Pad #2. You can simply select it at checkout.',
        timestamp: '2026-08-26T09:20:00.000Z',
      },
    ],
  },
];
