/**
 * SkyNav Autonomous Drone Delivery - Authoritative Product Catalog
 * =================================================================
 * Single source of truth for all products across Customer and Admin systems.
 * Guarantees 1:1 correspondence between:
 *   Product ID <-> Product Name <-> Category <-> Authentic Image <-> Pricing & Specs
 */

export interface CatalogProduct {
  id: string;
  name: string;
  slug: string;
  brand: string;
  categoryId: string;
  categoryName: string;
  subCategory: string;
  description: string;
  price: number;
  originalPrice: number;
  discountPercent: number;
  currency: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  stockCount: number;
  isDroneEligible: boolean;
  weightGrams: number;
  dimensions: string;
  deliveryMins: number;
  badge?: string;
  image: string;
  images: string[];
  tags: string[];
  specs: Record<string, string>;
  features: string[];
}

export interface CatalogCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  image: string;
  icon: string;
  displayOrder: number;
}

export const MASTER_CATEGORIES: CatalogCategory[] = [
  {
    id: 'cat_food',
    name: 'Hot Meals & Food',
    slug: 'Food',
    description: 'Fresh chef-crafted meals, authentic South Indian breakfast, and hot specialties delivered in 65°C thermal pods.',
    image: '/images/products/masala_dosa.jpg',
    icon: 'Utensils',
    displayOrder: 1,
  },
  {
    id: 'cat_med',
    name: 'Medicine & Health',
    slug: 'Medicine',
    description: 'Emergency trauma response kits, analgesics, test strips, inhalers, and urgent medical supplies.',
    image: '/images/products/first_aid_kit.jpg',
    icon: 'Pill',
    displayOrder: 2,
  },
  {
    id: 'cat_groc',
    name: 'Fresh Groceries',
    slug: 'Groceries',
    description: 'Fresh farm pasteurized milk, aromatic Coimbatore filter coffee, pantry staples, and kitchen essentials.',
    image: '/images/products/filter_coffee.jpg',
    icon: 'ShoppingBag',
    displayOrder: 3,
  },
  {
    id: 'cat_elec',
    name: 'Tech & Electronics',
    slug: 'Electronics',
    description: 'Ultra-fast GaN chargers, heavy-duty emergency power banks, and certified durable cables.',
    image: '/images/products/gan_charger.jpg',
    icon: 'Zap',
    displayOrder: 4,
  },
  {
    id: 'cat_doc',
    name: 'Instant Documents',
    slug: 'Documents',
    description: 'Tamper-evident biometric sealed pouches for urgent contracts, certificates, and notarized deeds.',
    image: '/images/products/legal_document_pouch.jpg',
    icon: 'FileText',
    displayOrder: 5,
  },
  {
    id: 'cat_other',
    name: 'Daily Essentials',
    slug: 'Other',
    description: 'Traditional cold-pressed cooking oils, home lifestyle goods, and urgent daily convenience items.',
    image: '/images/products/cold_pressed_oil.jpg',
    icon: 'Sparkles',
    displayOrder: 6,
  },
];

export const MASTER_PRODUCTS: CatalogProduct[] = [
  // ── 1. SOUTH INDIAN FOOD & HOT MEALS (cat_food) ─────────────────────────
  {
    id: 'prod_food_2',
    name: 'Kovai Crispy Masala Dosa & Sambar Breakfast Box',
    slug: 'kovai-crispy-masala-dosa-breakfast-box',
    brand: 'Kovai Kitchen Direct',
    categoryId: 'cat_food',
    categoryName: 'Hot Meals & Food',
    subCategory: 'Breakfast Combos',
    description: 'Crisp golden brown dosa filled with spiced potato masala, served steaming hot at 65°C with coconut chutney and piping hot drumstick sambar.',
    price: 180.00,
    originalPrice: 220.00,
    discountPercent: 18,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 520,
    inStock: true,
    stockCount: 30,
    isDroneEligible: true,
    weightGrams: 550,
    dimensions: '22 x 18 x 8 cm',
    deliveryMins: 11,
    badge: 'Hot In-Flight Pod 65°C',
    image: '/images/products/masala_dosa.jpg',
    images: [
      '/images/products/masala_dosa.jpg',
      'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['masala-dosa', 'dosa', 'breakfast', 'south-indian', 'hot-meal'],
    specs: {
      'Packaging': 'Thermal Lock 65°C Pod',
      'Includes': '2x Masala Dosa, Drumstick Sambar (200ml), Chutney',
      'Weight': '550g',
    },
    features: ['Crisp golden dosa crust', 'Spiced potato onion filling', 'Arrives piping hot in heated drone pod'],
  },
  {
    id: 'prod_food_dosa_plain',
    name: 'Sri Krishna Pure Ghee Roast Plain Dosa & Chutney Set',
    slug: 'sri-krishna-ghee-roast-plain-dosa-set',
    brand: 'Sri Krishna Sweets & Tiffins',
    categoryId: 'cat_food',
    categoryName: 'Hot Meals & Food',
    subCategory: 'Breakfast Combos',
    description: 'Paper-thin golden crepe roasted with pure desi cow ghee on cast iron, accompanied by coconut chutney, tomato chutney, and aromatic sambar.',
    price: 140.00,
    originalPrice: 175.00,
    discountPercent: 20,
    currency: 'INR',
    rating: 4.85,
    reviewCount: 310,
    inStock: true,
    stockCount: 35,
    isDroneEligible: true,
    weightGrams: 420,
    dimensions: '22 x 18 x 6 cm',
    deliveryMins: 10,
    badge: 'Pure Desi Ghee',
    image: '/images/products/plain_dosa.jpg',
    images: [
      '/images/products/plain_dosa.jpg',
      'https://images.unsplash.com/photo-1694849789325-914b71ab4075?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['plain-dosa', 'ghee-roast', 'dosa', 'breakfast', 'south-indian'],
    specs: {
      'Preparation': '100% Pure Desi Ghee on Cast Iron Tawa',
      'Accompaniments': 'Coconut Chutney (100ml), Tomato Chutney, Sambar',
      'Weight': '420g',
    },
    features: ['Ultra-crispy paper roast texture', 'Aromatic desi ghee aroma', 'Steam-release container retains crispness'],
  },
  {
    id: 'prod_food_idli',
    name: 'Malleswaram Steamed Fluffy Rice Idli (4 Pcs) & Coconut Chutney',
    slug: 'malleswaram-steamed-fluffy-rice-idli-4pcs',
    brand: 'Kovai Kitchen Direct',
    categoryId: 'cat_food',
    categoryName: 'Hot Meals & Food',
    subCategory: 'Breakfast Combos',
    description: 'Four ultra-soft melt-in-mouth steamed fermented rice and black gram idlis served piping hot with freshly grated coconut chutney and shallot sambar.',
    price: 120.00,
    originalPrice: 150.00,
    discountPercent: 20,
    currency: 'INR',
    rating: 4.92,
    reviewCount: 640,
    inStock: true,
    stockCount: 45,
    isDroneEligible: true,
    weightGrams: 480,
    dimensions: '18 x 18 x 6 cm',
    deliveryMins: 9,
    badge: 'Breakfast Staple',
    image: '/images/products/steamed_idli.jpg',
    images: [
      '/images/products/steamed_idli.jpg',
      'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['idli', 'steamed', 'breakfast', 'south-indian', 'healthy'],
    specs: {
      'Portion': '4 Extra-Fluffy Steamed Idlis',
      'Chutney': 'Fresh Stone-Ground Coconut Chutney',
      'Weight': '480g',
    },
    features: ['100% Fermented batter steamed fresh', 'Zero oil healthy meal', 'Delivered warm and moist'],
  },
  {
    id: 'prod_food_vada',
    name: 'Crispy Golden Medu Vada (3 Pcs) & Chutney Trio',
    slug: 'crispy-golden-medu-vada-3pcs',
    brand: 'Sri Anand Bhavan',
    categoryId: 'cat_food',
    categoryName: 'Hot Meals & Food',
    subCategory: 'Snacks & Savories',
    description: 'Crisp golden brown urad dal lentil fritters spiced with whole black peppercorns, curry leaves, and ginger. Served with a trio of chutneys.',
    price: 110.00,
    originalPrice: 140.00,
    discountPercent: 21,
    currency: 'INR',
    rating: 4.88,
    reviewCount: 420,
    inStock: true,
    stockCount: 40,
    isDroneEligible: true,
    weightGrams: 360,
    dimensions: '18 x 14 x 6 cm',
    deliveryMins: 10,
    badge: 'Extra Crunchy',
    image: '/images/products/medu_vada.jpg',
    images: [
      '/images/products/medu_vada.jpg',
      'https://images.unsplash.com/photo-1730191843435-073792ba22bc?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['vada', 'medu-vada', 'snack', 'breakfast', 'south-indian'],
    specs: {
      'Pieces': '3 Large Handcrafted Vadas',
      'Texture': 'Crunchy Outer Crust, Fluffy Center',
      'Weight': '360g',
    },
    features: ['Golden fried in pure cold-pressed oil', 'Peppercorn & ginger seasoning', 'Packaged in vented heat pouch'],
  },
  {
    id: 'prod_food_sambar',
    name: 'Traditional Tamil Nadu Drumstick Sambar Pot (500ml)',
    slug: 'traditional-tamil-nadu-drumstick-sambar-pot',
    brand: 'Kovai Kitchen Direct',
    categoryId: 'cat_food',
    categoryName: 'Hot Meals & Food',
    subCategory: 'Curries & Accompaniments',
    description: 'Slow-cooked toor dal stew simmered with fresh farm drumsticks, baby shallots, ripe tomatoes, tamarind, and fragrant roasted stone-ground sambar podi.',
    price: 95.00,
    originalPrice: 120.00,
    discountPercent: 21,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 280,
    inStock: true,
    stockCount: 50,
    isDroneEligible: true,
    weightGrams: 540,
    dimensions: '14 x 14 x 10 cm',
    deliveryMins: 9,
    badge: 'Freshly Simmered',
    image: '/images/products/sambar_pot.jpg',
    images: [
      '/images/products/sambar_pot.jpg',
      'https://images.unsplash.com/photo-1632104667384-06f58cb7ad44?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['sambar', 'curry', 'drumstick', 'dal', 'south-indian'],
    specs: {
      'Volume': '500ml Leak-Proof Thermal Tub',
      'Ingredients': 'Toor Dal, Drumsticks, Madras Onions, Tamarind, Sambar Podi',
      'Weight': '540g',
    },
    features: ['Simmered with traditional wood-pressed oil tempering', 'Rich aroma and balanced tanginess', 'Double-sealed against flight turbulence'],
  },
  {
    id: 'prod_food_meals',
    name: 'South Indian Traditional Executive Meals Thali',
    slug: 'south-indian-traditional-executive-meals-thali',
    brand: 'Sri Anand Bhavan',
    categoryId: 'cat_food',
    categoryName: 'Hot Meals & Food',
    subCategory: 'Lunch & Dinner Thali',
    description: 'Lavish traditional South Indian lunch feast: Steamed Ponni boiled rice, drumstick sambar, tomato rasam, vegetable poriyal, kootu, fresh curd, and crisp appalam.',
    price: 220.00,
    originalPrice: 260.00,
    discountPercent: 15,
    currency: 'INR',
    rating: 4.95,
    reviewCount: 780,
    inStock: true,
    stockCount: 30,
    isDroneEligible: true,
    weightGrams: 950,
    dimensions: '26 x 26 x 7 cm',
    deliveryMins: 12,
    badge: 'Complete Feast',
    image: '/images/products/south_indian_thali.jpg',
    images: [
      '/images/products/south_indian_thali.jpg',
      'https://images.unsplash.com/photo-1680993032090-1ef7ea9b51e5?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['thali', 'meals', 'lunch', 'rice', 'south-indian', 'feast'],
    specs: {
      'Containers': '7-Section Compartmental Bento Pod',
      'Included': 'Rice (400g), Sambar, Rasam, Kootu, Poriyal, Curd, Appalam',
      'Weight': '950g',
    },
    features: ['Complete balanced nutrition', 'Packed in insulated sectioned tray', 'Arrives at ideal eating temperature'],
  },
  {
    id: 'prod_food_1',
    name: 'Anand Bhavan Ghee Mysore Pak Special Gift Box (400g)',
    slug: 'anand-bhavan-ghee-mysore-pak-400g',
    brand: 'Sri Anand Bhavan',
    categoryId: 'cat_food',
    categoryName: 'Hot Meals & Food',
    subCategory: 'Traditional Sweets',
    description: 'Melt-in-mouth traditional Coimbatore sweet crafted with pure desi cow ghee, roasted gram flour, and cardamom. Packaged in an ornate gift presentation box.',
    price: 420.00,
    originalPrice: 480.00,
    discountPercent: 12,
    currency: 'INR',
    rating: 5.0,
    reviewCount: 390,
    inStock: true,
    stockCount: 40,
    isDroneEligible: true,
    weightGrams: 450,
    dimensions: '18 x 14 x 5 cm',
    deliveryMins: 13,
    badge: 'Festive Delight',
    image: '/images/products/ghee_mysore_pak.jpg',
    images: [
      '/images/products/ghee_mysore_pak.jpg',
      'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['sweets', 'mysore-pak', 'ghee', 'coimbatore', 'dessert'],
    specs: {
      'Weight': '400g Net',
      'Ingredients': 'Pure Desi Cow Ghee, Gram Flour, Sugar, Cardamom',
      'Shelf Life': '15 Days',
    },
    features: ['Rich golden-yellow porous texture', '100% Desi Ghee purity', 'Crush-resistant rigid gift packaging'],
  },
  {
    id: 'prod_food_snacks',
    name: 'Kovai Crispy Hot Butter Murukku & Mixture Combo (300g)',
    slug: 'kovai-crispy-butter-murukku-mixture-combo',
    brand: 'Heritage Kovai Organics',
    categoryId: 'cat_food',
    categoryName: 'Hot Meals & Food',
    subCategory: 'Snacks & Savories',
    description: 'Authentic handmade crunchy spiral rice flour chakli murukku flavored with cumin and sesame seeds, paired with spicy crunchy South Indian mixture.',
    price: 130.00,
    originalPrice: 160.00,
    discountPercent: 19,
    currency: 'INR',
    rating: 4.82,
    reviewCount: 240,
    inStock: true,
    stockCount: 60,
    isDroneEligible: true,
    weightGrams: 340,
    dimensions: '16 x 12 x 8 cm',
    deliveryMins: 10,
    badge: 'Teatime Favorite',
    image: '/images/products/butter_murukku.jpg',
    images: [
      '/images/products/butter_murukku.jpg',
      'https://images.unsplash.com/photo-1709091052718-3cb8a990edfa?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['murukku', 'mixture', 'snacks', 'savory', 'coimbatore'],
    specs: {
      'Net Weight': '300g (150g Murukku + 150g Mixture)',
      'Type': 'Crunchy Savory Snack Combo',
      'Shelf Life': '30 Days',
    },
    features: ['Wood-pressed oil frying', 'Zero palm oil or artificial colors', 'Nitrogen-flushed pack retains fresh crunch'],
  },

  // ── 2. FRESH GROCERIES & BEVERAGES (cat_groc) ───────────────────────────
  {
    id: 'prod_groc_1',
    name: 'Coimbatore Authentic Filter Coffee Blend (500g)',
    slug: 'coimbatore-authentic-filter-coffee-blend-500g',
    brand: 'Kovai Coffee Works',
    categoryId: 'cat_groc',
    categoryName: 'Fresh Groceries',
    subCategory: 'Beverages',
    description: 'Traditional 80:20 plantation peaberry coffee beans and roasted chicory freshly ground for a thick, aromatic, and frothy South Indian davarah brew.',
    price: 340.00,
    originalPrice: 420.00,
    discountPercent: 19,
    currency: 'INR',
    rating: 4.94,
    reviewCount: 680,
    inStock: true,
    stockCount: 65,
    isDroneEligible: true,
    weightGrams: 520,
    dimensions: '16 x 10 x 6 cm',
    deliveryMins: 11,
    badge: 'Local Favorite',
    image: '/images/products/filter_coffee.jpg',
    images: [
      '/images/products/filter_coffee.jpg',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['coffee', 'filter-coffee', 'coimbatore', 'beverages', 'south-indian'],
    specs: {
      'Roast': 'Medium-Dark Slow Roast',
      'Blend Ratio': '80% Premium Arabica & Robusta : 20% Chicory',
      'Origin': 'Western Ghats / Anamalai Foothills',
    },
    features: ['Freshly ground daily', 'Aroma lock valve pouch', 'Rich crema and authentic South Indian kick'],
  },
  {
    id: 'prod_groc_2',
    name: 'Aavin Fresh Farm Pasteurized Pure Milk (1L x 2)',
    slug: 'aavin-fresh-farm-pure-milk-2l',
    brand: 'Aavin Tamil Nadu',
    categoryId: 'cat_groc',
    categoryName: 'Fresh Groceries',
    subCategory: 'Dairy',
    description: 'Chilled pasteurized homogenized cow milk delivered in insulated cold-chain flight thermal pods direct from the Coimbatore local dairy union.',
    price: 120.00,
    originalPrice: 130.00,
    discountPercent: 8,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 1100,
    inStock: true,
    stockCount: 120,
    isDroneEligible: true,
    weightGrams: 1050,
    dimensions: '20 x 14 x 10 cm',
    deliveryMins: 10,
    badge: 'Fresh Daily',
    image: '/images/products/aavin_milk.jpg',
    images: [
      '/images/products/aavin_milk.jpg',
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['milk', 'aavin', 'fresh', 'dairy', 'coimbatore'],
    specs: {
      'Volume': '2 Litres (1L x 2 Pouches)',
      'Fat Content': '4.5% Standardized Cow Milk',
      'Transit Temperature': 'Cold Chain 4°C Pod',
    },
    features: ['Pure unadulterated pasteurized milk', 'Chilled flight pod prevents spoilage', 'Morning farm fresh source'],
  },

  // ── 3. MEDICINE & URGENT HEALTH (cat_med) ───────────────────────────────
  {
    id: 'prod_med_1',
    name: 'Apollo Rapid Emergency First-Aid Trauma Kit',
    slug: 'apollo-rapid-emergency-first-aid-trauma-kit',
    brand: 'Apollo Pharmacy',
    categoryId: 'cat_med',
    categoryName: 'Medicine & Health',
    subCategory: 'Emergency Care',
    description: 'Sterile hospital-grade emergency trauma pack with medical shears, tourniquet, antiseptic solution, sterile gauze dressings, and burn shield.',
    price: 499.00,
    originalPrice: 699.00,
    discountPercent: 28,
    currency: 'INR',
    rating: 5.0,
    reviewCount: 512,
    inStock: true,
    stockCount: 75,
    isDroneEligible: true,
    weightGrams: 450,
    dimensions: '18 x 12 x 8 cm',
    deliveryMins: 8,
    badge: 'Urgent Dispatch',
    image: '/images/products/first_aid_kit.jpg',
    images: [
      '/images/products/first_aid_kit.jpg',
      'https://images.unsplash.com/photo-1624638760852-8ede1666ab07?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['trauma', 'first-aid', 'apollo', 'sterile', 'emergency'],
    specs: {
      'Certification': 'ISO 13485 / Apollo Healthcare Certified',
      'Contents': '38 Individually Sealed Sterile Items',
      'Packaging': 'Waterproof Kevlar High-Vis Pouch',
    },
    features: ['Rapid 8-minute air dispatch', 'Complete trauma stabilization tools', 'Tamper-evident hygiene seal'],
  },
  {
    id: 'prod_med_2',
    name: 'Amrutanjan Rapid Pain Relief & Vaporub Duo Pack',
    slug: 'amrutanjan-rapid-pain-relief-duo',
    brand: 'Amrutanjan Health',
    categoryId: 'cat_med',
    categoryName: 'Medicine & Health',
    subCategory: 'Pain Care',
    description: 'Time-tested ayurvedic pain balm and eucalyptus chest rub for fast natural relief from throbbing headache, chest congestion, and muscle aches.',
    price: 199.00,
    originalPrice: 260.00,
    discountPercent: 23,
    currency: 'INR',
    rating: 4.85,
    reviewCount: 420,
    inStock: true,
    stockCount: 90,
    isDroneEligible: true,
    weightGrams: 150,
    dimensions: '10 x 6 x 5 cm',
    deliveryMins: 9,
    badge: 'Essential Care',
    image: '/images/products/pain_relief_balm.jpg',
    images: [
      '/images/products/pain_relief_balm.jpg',
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['pain-relief', 'balm', 'ayurvedic', 'amrutanjan', 'medicine'],
    specs: {
      'Form': 'Herbal Medicated Balm & Chest Rub',
      'Net Weight': '50g + 30g',
      'Active Herbs': 'Pudina Ka Phool, Gandhapura Oil, Nilgiri Eucalyptus',
    },
    features: ['100% Ayurvedic herbal formulation', 'Instant heating and cooling action', 'Pocket-friendly safe cap'],
  },

  // ── 4. TECH & ELECTRONICS (cat_elec) ────────────────────────────────────
  {
    id: 'prod_elec_1',
    name: 'BoAt Storm GaN 65W Rapid Dual-Port Fast Charger',
    slug: 'boat-storm-gan-65w-rapid-fast-charger',
    brand: 'boAt',
    categoryId: 'cat_elec',
    categoryName: 'Tech & Electronics',
    subCategory: 'Charging & Power',
    description: 'Ultra-compact Gallium Nitride 65W fast charger with dual Type-C and USB-A power delivery for Indian smartphones, iPads, and high-performance laptops.',
    price: 1299.00,
    originalPrice: 1999.00,
    discountPercent: 35,
    currency: 'INR',
    rating: 4.9,
    reviewCount: 342,
    inStock: true,
    stockCount: 50,
    isDroneEligible: true,
    weightGrams: 180,
    dimensions: '5.2 x 4.8 x 3.1 cm',
    deliveryMins: 11,
    badge: 'Best Seller',
    image: '/images/products/gan_charger.jpg',
    images: [
      '/images/products/gan_charger.jpg',
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['gan', 'fast-charger', 'boat', 'electronics', 'type-c'],
    specs: {
      'Wattage': '65W GaN III Fast Power Delivery',
      'Ports': '2x USB Type-C (65W Max), 1x USB-A (22.5W QC3.0)',
      'Weight': '180g',
    },
    features: ['Smart IC heat protection', 'Charges laptops & mobiles simultaneously', 'Compact travel-friendly build'],
  },
  {
    id: 'prod_elec_2',
    name: 'Syska 20000mAh Heavy Duty Power Bank',
    slug: 'syska-20000mah-power-bank',
    brand: 'Syska',
    categoryId: 'cat_elec',
    categoryName: 'Tech & Electronics',
    subCategory: 'Power Accessories',
    description: 'High-density 20000mAh external battery pack with 22.5W two-way fast charging, triple device output, and LED digital capacity indicator.',
    price: 1499.00,
    originalPrice: 2499.00,
    discountPercent: 40,
    currency: 'INR',
    rating: 4.8,
    reviewCount: 218,
    inStock: true,
    stockCount: 35,
    isDroneEligible: true,
    weightGrams: 420,
    dimensions: '14.2 x 6.8 x 2.8 cm',
    deliveryMins: 12,
    badge: 'High Capacity',
    image: '/images/products/power_bank.jpg',
    images: [
      '/images/products/power_bank.jpg',
      'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['powerbank', 'syska', 'battery', 'fast-charge', 'electronics'],
    specs: {
      'Battery Capacity': '20,000mAh Li-Polymer',
      'Output Speed': '22.5W Two-Way Fast Charge',
      'Ports': 'Type-C PD In/Out, 2x USB-A QC Fast Outputs',
    },
    features: ['Over-charge and short-circuit safety', 'Airline approved capacity', 'LED percentage indicator'],
  },

  // ── 5. INSTANT DOCUMENTS (cat_doc) ──────────────────────────────────────
  {
    id: 'prod_doc_1',
    name: 'Biometric Sealed Legal Document Security Pouch',
    slug: 'biometric-sealed-legal-document-pouch',
    brand: 'SkyNav Secure',
    categoryId: 'cat_doc',
    categoryName: 'Instant Documents',
    subCategory: 'Legal Courier',
    description: 'Tamper-evident waterproof polymer courier envelope with dynamic QR tracking seal, designed for confidential contracts, deeds, and certificates.',
    price: 250.00,
    originalPrice: 350.00,
    discountPercent: 28,
    currency: 'INR',
    rating: 4.92,
    reviewCount: 160,
    inStock: true,
    stockCount: 100,
    isDroneEligible: true,
    weightGrams: 120,
    dimensions: '32 x 24 x 1 cm',
    deliveryMins: 8,
    badge: 'Secure Seal',
    image: '/images/products/legal_document_pouch.jpg',
    images: [
      '/images/products/legal_document_pouch.jpg',
      'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['document', 'legal', 'secure', 'confidential', 'courier'],
    specs: {
      'Security Level': 'Tamper-Evident VOID Seal + Dynamic Delivery PIN',
      'Capacity': 'Up to 60 Heavy A4 Legal Sheets',
      'Enclosure': 'IP68 Submersible Waterproof Polymer',
    },
    features: ['End-to-end GPS flight chain of custody', 'Instant permanent PIN handover verification', 'Tear-proof waterproof construction'],
  },

  // ── 6. DAILY ESSENTIALS (cat_other) ─────────────────────────────────────
  {
    id: 'prod_oth_1',
    name: 'Kovai Heritage Cold-Pressed Sesame Gingelly Oil (500ml)',
    slug: 'kovai-heritage-sesame-gingelly-oil-500ml',
    brand: 'Heritage Kovai Organics',
    categoryId: 'cat_other',
    categoryName: 'Daily Essentials',
    subCategory: 'Cooking Essentials',
    description: 'Traditional wood-pressed (Vaagai Mara Chekku) unrefined black sesame oil naturally sweetened with organic palm jaggery. Unfiltered and rich in antioxidants.',
    price: 260.00,
    originalPrice: 320.00,
    discountPercent: 19,
    currency: 'INR',
    rating: 4.88,
    reviewCount: 290,
    inStock: true,
    stockCount: 55,
    isDroneEligible: true,
    weightGrams: 520,
    dimensions: '18 x 7 x 7 cm',
    deliveryMins: 11,
    badge: '100% Organic',
    image: '/images/products/cold_pressed_oil.jpg',
    images: [
      '/images/products/cold_pressed_oil.jpg',
      'https://images.unsplash.com/photo-1552592074-ea7a91b851b3?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['oil', 'gingelly', 'sesame', 'cold-pressed', 'organic'],
    specs: {
      'Extraction Method': 'Traditional Wood Vaagai Chekku Slow Extraction',
      'Volume': '500ml Glass Dispenser Bottle',
      'Purity': '100% Raw Unfiltered Virgin Sesame Oil',
    },
    features: ['Extracted with organic palm jaggery', 'Cold-pressed below 40°C retains vital nutrients', 'Authentic nutty aroma for South Indian cooking'],
  },
];
