import * as THREE from 'three';

export interface StoryScene {
  id: number;
  sceneNumber: string; // e.g. "PHASE 01"
  title: string;
  badge: string;
  shortDesc: string;
  explanation: string;
  duration: number; // in seconds
  cameraMode: 'operations' | 'follow' | 'fpv' | 'top' | 'customer' | 'obstacle' | 'hub';
  flightPhase: 'idle' | 'preflight' | 'takeoff' | 'climb' | 'cruise' | 'hover' | 'descent' | 'landing' | 'delivered' | 'return' | 'completed';
  status: 'normal' | 'warning' | 'critical' | 'delivery' | 'return';
  dronePos: THREE.Vector3;
  droneRot: THREE.Euler;
  altitude: number; // in meters
  speed: number; // in km/h
  heading: number; // in degrees
  battery: number; // in %
  temperature: number; // in °C
  signalRssi: number; // in -dBm
  distanceTraveledKm: number;
  etaMinutes: number;
  payloadAttached: boolean;
  obstacleScanning: boolean;
  isObstaclePresent: boolean;
  isRerouted: boolean;
  decisionAlert?: {
    type: 'info' | 'warning' | 'reroute' | 'emergency';
    title: string;
    details: string;
    reason: string;
  };
  eventLog: string;
}

export interface MultiDroneSimState {
  id: string;
  name: string;
  missionId: string;
  color: string;
  startPos: THREE.Vector3;
  targetPos: THREE.Vector3;
  currentPos: THREE.Vector3;
  altitude: number;
  speed: number;
  battery: number;
  status: string;
  progress: number;
}

// Full 26-Phase Synchronized Autonomous Delivery Story Engine
export const AUTONOMOUS_DELIVERY_STORY: StoryScene[] = [
  {
    id: 1,
    sceneNumber: 'PHASE 01',
    title: 'CUSTOMER PLACES ORDER',
    badge: 'Customer Dispatch',
    shortDesc: 'Customer initiates emergency medical supply order via app.',
    explanation: 'Order ORD-10482 generated for KMCH Cardiology Center. Destination: RS Puram Sector 4. High-priority parcel payload: 2.8 kg.',
    duration: 3.5,
    cameraMode: 'customer',
    flightPhase: 'idle',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 95,
    temperature: 28,
    signalRssi: 64,
    distanceTraveledKm: 0,
    etaMinutes: 8.5,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    decisionAlert: {
      type: 'info',
      title: 'ORDER INGESTED BY DISPATCH ENGINE',
      details: 'ORD-10482 [Medical Emergency Kit - 2.8kg]',
      reason: 'Automated corridor reservation initiated.',
    },
    eventLog: '12:03:10 — Order ORD-10482 received from KMCH Care Center.',
  },
  {
    id: 2,
    sceneNumber: 'PHASE 02',
    title: 'ORDER RECEIVED & VERIFIED',
    badge: 'Dispatch Ingestion',
    shortDesc: 'SkyNav Operations platform authenticates order details & payload weights.',
    explanation: 'Digital verification confirmed. Payment settlement verified. Priority tag: CRITICAL MEDICAL. Destination geofence checked: CLEAR.',
    duration: 3.0,
    cameraMode: 'operations',
    flightPhase: 'idle',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 95,
    temperature: 28,
    signalRssi: 64,
    distanceTraveledKm: 0,
    etaMinutes: 8.4,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:03:12 — Order security & digital cryptographic signature verified.',
  },
  {
    id: 3,
    sceneNumber: 'PHASE 03',
    title: 'MISSION CREATED & DECONFLICTED',
    badge: 'Mission Engine',
    shortDesc: 'Mission Engine generates 4D trajectory MIS-20491.',
    explanation: 'Automated flight corridor deconfliction verified with DGCA DigitalSky. Corridor 4-Alpha allocated with 120m vertical ceiling.',
    duration: 3.5,
    cameraMode: 'operations',
    flightPhase: 'idle',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 95,
    temperature: 28,
    signalRssi: 64,
    distanceTraveledKm: 0,
    etaMinutes: 8.2,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    decisionAlert: {
      type: 'info',
      title: 'MISSION INITIALIZED: MIS-20491',
      details: 'Corridor: 4-Alpha • Airway Ceiling: 120m AGL',
      reason: 'Zero spatial conflict with other active corridor UAVs.',
    },
    eventLog: '12:03:14 — Mission MIS-20491 created with high-priority airspace reservation.',
  },
  {
    id: 4,
    sceneNumber: 'PHASE 04',
    title: 'PACKAGE PREPARED & BARCODE SCANNED',
    badge: 'Warehouse Automation',
    shortDesc: 'Automated warehouse conveyor laser scans package barcode.',
    explanation: 'Barcode verified. Weight calibration confirms 2.80 kg. Medical thermal insulation armed at 4°C active cooling.',
    duration: 3.5,
    cameraMode: 'hub',
    flightPhase: 'idle',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 95,
    temperature: 29,
    signalRssi: 62,
    distanceTraveledKm: 0,
    etaMinutes: 8.0,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:03:18 — Package scanned & weight calibrated at Warehouse Bay 01.',
  },
  {
    id: 5,
    sceneNumber: 'PHASE 05',
    title: 'SMART DRONE SELECTION',
    badge: 'Fleet Allocation',
    shortDesc: 'Multi-factor algorithm evaluates fleet and selects D-024.',
    explanation: 'Ranked #1 among 14 ready drones: Distance (2.4km ✓), Battery (95% ✓), Payload (5.0kg ✓), Motor Health (98% ✓), Weather tolerance (✓).',
    duration: 4.0,
    cameraMode: 'hub',
    flightPhase: 'idle',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 95,
    temperature: 29,
    signalRssi: 62,
    distanceTraveledKm: 0,
    etaMinutes: 7.9,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    decisionAlert: {
      type: 'info',
      title: 'WHY THIS DRONE? (D-024 SELECTED)',
      details: 'Battery: 95% • Cap: 5.0kg • Health: 98% • Confidence: 96%',
      reason: 'Optimal efficiency score for emergency cardiology route.',
    },
    eventLog: '12:03:22 — Asset D-024 assigned to Mission MIS-20491.',
  },
  {
    id: 6,
    sceneNumber: 'PHASE 06',
    title: 'PRE-FLIGHT DIAGNOSTICS VERIFIED',
    badge: 'Avionics Check',
    shortDesc: 'Automated 24-point system diagnostics completed successfully.',
    explanation: 'Dual RTK GPS: LOCKED (28 Sats, HDOP 0.58). Battery cell variance: 0.01V. ESC motor currents: BALANCED. 5G telemetry link: NOMINAL (-62dBm).',
    duration: 4.0,
    cameraMode: 'follow',
    flightPhase: 'preflight',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 94,
    temperature: 30,
    signalRssi: 60,
    distanceTraveledKm: 0,
    etaMinutes: 7.8,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    decisionAlert: {
      type: 'info',
      title: 'PRE-FLIGHT DIAGNOSTICS PASSED (24/24)',
      details: 'Dual RTK: Fix (1.2cm) • ESC Motors: Balanced • Link: 5G Mesh',
      reason: 'All safety thresholds validated. Ready for takeoff.',
    },
    eventLog: '12:03:27 — Pre-flight check complete: 100% nominal systems.',
  },
  {
    id: 7,
    sceneNumber: 'PHASE 07',
    title: 'PACKAGE LOADED & SECURED',
    badge: 'Payload Locker',
    shortDesc: 'Cargo box locked into automated drone underbelly bay.',
    explanation: 'Electronic locking jaws clamp package securely. Center of gravity verified within ±2mm envelope.',
    duration: 3.5,
    cameraMode: 'follow',
    flightPhase: 'preflight',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 94,
    temperature: 30,
    signalRssi: 60,
    distanceTraveledKm: 0,
    etaMinutes: 7.7,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:03:30 — Cargo locker locked and CG verified.',
  },
  {
    id: 8,
    sceneNumber: 'PHASE 08',
    title: 'PROPELLERS START & SPOOL UP',
    badge: 'Propulsion Start',
    shortDesc: 'Motors spin up to 5,800 RPM. Navigation strobes pulsing.',
    explanation: 'Sinusoidal FOC drivers ramp up 4 BLDC motors smoothly. Acoustic noise profile nominal. Thrust balance confirmed.',
    duration: 3.5,
    cameraMode: 'follow',
    flightPhase: 'takeoff',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.5, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 1,
    speed: 2,
    heading: 0,
    battery: 93,
    temperature: 31,
    signalRssi: 60,
    distanceTraveledKm: 0,
    etaMinutes: 7.5,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:03:34 — Rotors spooled up to 5,800 RPM.',
  },
  {
    id: 9,
    sceneNumber: 'PHASE 09',
    title: 'AUTONOMOUS VERTICAL TAKEOFF',
    badge: 'Vertical Lift',
    shortDesc: 'Drone lifts off vertically from Hub Pad 1 to 20m AGL.',
    explanation: 'Smooth autonomous vertical climb initiated at +3.2 m/s. Pad clearance verified via downward optical sensors.',
    duration: 4.0,
    cameraMode: 'follow',
    flightPhase: 'takeoff',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 4, -33),
    droneRot: new THREE.Euler(-0.05, 0, 0),
    altitude: 20,
    speed: 14,
    heading: 0,
    battery: 92,
    temperature: 32,
    signalRssi: 60,
    distanceTraveledKm: 0.1,
    etaMinutes: 7.2,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:03:38 — Vertical takeoff nominal: Passed 20m AGL.',
  },
  {
    id: 10,
    sceneNumber: 'PHASE 10',
    title: 'TRANSITION CLIMB',
    badge: 'Corridor Climb',
    shortDesc: 'Climbing through 60m towards designated 80m corridor altitude.',
    explanation: 'Pitch angles forward 12°. Drone smoothly accelerates to 36 km/h while climbing towards designated airway.',
    duration: 4.0,
    cameraMode: 'operations',
    flightPhase: 'climb',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 14, -20),
    droneRot: new THREE.Euler(-0.15, 0, 0),
    altitude: 60,
    speed: 36,
    heading: 0,
    battery: 90,
    temperature: 34,
    signalRssi: 58,
    distanceTraveledKm: 0.5,
    etaMinutes: 6.5,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:03:52 — Transition climb to 60m AGL at 36 km/h.',
  },
  {
    id: 11,
    sceneNumber: 'PHASE 11',
    title: 'ROUTE CALCULATION & CORRIDOR LOCK',
    badge: 'Airway Alignment',
    shortDesc: 'Trajectory locked onto Peelamedu Airway 4-Alpha.',
    explanation: 'Autopilot engages full corridor precision tracking. Cross-track deviation < 0.3m under RTK lock.',
    duration: 3.5,
    cameraMode: 'operations',
    flightPhase: 'climb',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 16, -15),
    droneRot: new THREE.Euler(-0.12, 0, 0),
    altitude: 75,
    speed: 42,
    heading: 0,
    battery: 89,
    temperature: 35,
    signalRssi: 58,
    distanceTraveledKm: 0.8,
    etaMinutes: 5.8,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:04:02 — Corridor 4-Alpha locked with sub-meter tracking.',
  },
  {
    id: 12,
    sceneNumber: 'PHASE 12',
    title: 'CORRIDOR CRUISE AT 82m AGL',
    badge: 'Nominal Cruise',
    shortDesc: 'Cruising at 48 km/h. Real-time telemetry streaming.',
    explanation: 'Cruising smoothly at 82m AGL, 48 km/h. Forward pulsed LiDAR scanner active. Power consumption: 4.6% per km.',
    duration: 5.0,
    cameraMode: 'fpv',
    flightPhase: 'cruise',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 16, -10),
    droneRot: new THREE.Euler(-0.12, 0, 0),
    altitude: 82,
    speed: 48,
    heading: 0,
    battery: 87,
    temperature: 36,
    signalRssi: 56,
    distanceTraveledKm: 1.4,
    etaMinutes: 4.8,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:04:25 — Nominal cruise at 82m AGL (48 km/h).',
  },
  {
    id: 13,
    sceneNumber: 'PHASE 13',
    title: 'ENVIRONMENTAL WEATHER ANALYSIS',
    badge: 'Weather Sensor Sync',
    shortDesc: 'Crosswind gust (18 km/h NE) detected; autopilot compensates.',
    explanation: 'Onboard barometric & IMU sensors detect 18 km/h crosswind shear. Autopilot applies 3.2° crab angle to maintain flight corridor center.',
    duration: 4.0,
    cameraMode: 'follow',
    flightPhase: 'cruise',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 16, -5),
    droneRot: new THREE.Euler(-0.1, -0.05, 0.05),
    altitude: 81,
    speed: 46,
    heading: 356,
    battery: 85,
    temperature: 36,
    signalRssi: 56,
    distanceTraveledKm: 1.8,
    etaMinutes: 4.2,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:04:50 — Wind compensation applied (18 km/h crosswind).',
  },
  {
    id: 14,
    sceneNumber: 'PHASE 14',
    title: 'DYNAMIC OBSTACLE DETECTED',
    badge: 'LiDAR Alert',
    shortDesc: 'Forward LiDAR detects construction crane mast at 180m.',
    explanation: 'LiDAR returns identify unnotified crane structure encroaching flight corridor at 180m. Collision risk: 78%. Deceleration initiated.',
    duration: 4.5,
    cameraMode: 'obstacle',
    flightPhase: 'hover',
    status: 'warning',
    dronePos: new THREE.Vector3(0, 16, -2),
    droneRot: new THREE.Euler(0.05, 0, 0),
    altitude: 80,
    speed: 22,
    heading: 355,
    battery: 83,
    temperature: 37,
    signalRssi: 58,
    distanceTraveledKm: 2.1,
    etaMinutes: 4.0,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: true,
    isRerouted: false,
    decisionAlert: {
      type: 'warning',
      title: 'COLLISION PROXIMITY ALERT',
      details: 'Target: Construction Crane • Distance: 180m Ahead',
      reason: 'Collision probability exceeds safety threshold (78%).',
    },
    eventLog: '12:05:15 — Warning: Unscheduled crane obstacle detected at 180m.',
  },
  {
    id: 15,
    sceneNumber: 'PHASE 15',
    title: 'AUTONOMOUS DECISION (AI INSIGHT)',
    badge: 'Simulated AI Insight',
    shortDesc: 'Autonomous Rule Engine calculates lateral bypass vector.',
    explanation: 'Decision latency: 38ms. Action: Bank West 18°, offset +120m, maintain altitude 80m. Alternate trajectory evaluated 100% collision-free.',
    duration: 4.0,
    cameraMode: 'follow',
    flightPhase: 'hover',
    status: 'warning',
    dronePos: new THREE.Vector3(-2, 16, 2),
    droneRot: new THREE.Euler(0, 0.2, -0.15),
    altitude: 80,
    speed: 28,
    heading: 10,
    battery: 82,
    temperature: 37,
    signalRssi: 58,
    distanceTraveledKm: 2.3,
    etaMinutes: 3.8,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: true,
    isRerouted: true,
    decisionAlert: {
      type: 'reroute',
      title: 'AUTONOMOUS DECISION: LATERAL REROUTE',
      details: 'WHAT: Obstacle Ahead | WHY: Risk 78% | DECISION: Reroute West',
      reason: 'Safe separation restored (+120m clearance).',
    },
    eventLog: '12:05:18 — Simulated AI Insight: Lateral bypass vector generated.',
  },
  {
    id: 16,
    sceneNumber: 'PHASE 16',
    title: 'DYNAMIC REROUTING MANEUVER',
    badge: 'Avoidance Maneuver',
    shortDesc: 'Drone banks 18° left, clearing the obstacle envelope.',
    explanation: 'Drone smoothly tracks alternate waypoint bypass. Clearance from crane exceeds 120m buffer. Airspeed recovers to 42 km/h.',
    duration: 5.0,
    cameraMode: 'follow',
    flightPhase: 'cruise',
    status: 'normal',
    dronePos: new THREE.Vector3(-7, 16, 8),
    droneRot: new THREE.Euler(-0.08, 0.25, -0.2),
    altitude: 80,
    speed: 42,
    heading: 15,
    battery: 80,
    temperature: 38,
    signalRssi: 56,
    distanceTraveledKm: 2.6,
    etaMinutes: 3.2,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: true,
    isRerouted: true,
    eventLog: '12:05:30 — Obstacle cleared with 120m lateral separation.',
  },
  {
    id: 17,
    sceneNumber: 'PHASE 17',
    title: 'REJOINING PRIMARY CORRIDOR',
    badge: 'Corridor Rejoin',
    shortDesc: 'Drone turns smoothly back into nominal delivery corridor.',
    explanation: 'Re-entering primary airway. Autopilot updates remaining ETA to 2.4 minutes. All systems nominal.',
    duration: 4.0,
    cameraMode: 'operations',
    flightPhase: 'cruise',
    status: 'normal',
    dronePos: new THREE.Vector3(-3, 14, 18),
    droneRot: new THREE.Euler(-0.1, -0.15, 0.1),
    altitude: 70,
    speed: 44,
    heading: 350,
    battery: 78,
    temperature: 37,
    signalRssi: 56,
    distanceTraveledKm: 3.0,
    etaMinutes: 2.4,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: false,
    isRerouted: true,
    eventLog: '12:05:55 — Primary delivery corridor safely rejoined.',
  },
  {
    id: 18,
    sceneNumber: 'PHASE 18',
    title: 'DESTINATION APPROACH',
    badge: 'Approach Phase',
    shortDesc: 'Approaching RS Puram Sector 4 landing zone. Altitude stepping down.',
    explanation: 'Entering terminal approach area. Altitude decreases from 70m -> 35m -> 15m. Speed throttles back to 16 km/h.',
    duration: 4.5,
    cameraMode: 'customer',
    flightPhase: 'descent',
    status: 'delivery',
    dronePos: new THREE.Vector3(-1, 8, 28),
    droneRot: new THREE.Euler(0.08, 0, 0),
    altitude: 35,
    speed: 16,
    heading: 0,
    battery: 76,
    temperature: 36,
    signalRssi: 54,
    distanceTraveledKm: 3.3,
    etaMinutes: 1.2,
    payloadAttached: true,
    obstacleScanning: true,
    isObstaclePresent: false,
    isRerouted: true,
    eventLog: '12:06:20 — Terminal area approach: Deceleration nominal.',
  },
  {
    id: 19,
    sceneNumber: 'PHASE 19',
    title: 'LANDING ZONE IDENTIFIED (OPTICAL LOCK)',
    badge: 'Computer Vision',
    shortDesc: 'Downward camera identifies and locks onto green target pad.',
    explanation: 'Optical flow algorithm recognizes smart landing pad QR fiducials. Horizontal tracking error: 0.03m. Surface confirmed level.',
    duration: 4.0,
    cameraMode: 'follow',
    flightPhase: 'hover',
    status: 'delivery',
    dronePos: new THREE.Vector3(0, 3.5, 38),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 8.0,
    speed: 4,
    heading: 0,
    battery: 75,
    temperature: 35,
    signalRssi: 52,
    distanceTraveledKm: 3.5,
    etaMinutes: 0.5,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: true,
    decisionAlert: {
      type: 'info',
      title: 'LANDING ZONE IDENTIFIED & LOCKED',
      details: 'Target Deviation: 0.03m • Surface: Level & Safe',
      reason: 'Ground clearance verified. Commencing precision descent.',
    },
    eventLog: '12:06:45 — Optical landing zone acquired with centimeter lock.',
  },
  {
    id: 20,
    sceneNumber: 'PHASE 20',
    title: 'ALIGNMENT & STABLE HOVER',
    badge: 'Precision Hover',
    shortDesc: 'Drone hovers stably at 3.0m AGL directly over target center.',
    explanation: 'Laser altimeter active. 3.0m hover maintained against ground effect turbulence. Cargo winch ready for release.',
    duration: 3.5,
    cameraMode: 'fpv',
    flightPhase: 'hover',
    status: 'delivery',
    dronePos: new THREE.Vector3(0, 2.5, 38),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 3.0,
    speed: 0,
    heading: 0,
    battery: 75,
    temperature: 35,
    signalRssi: 52,
    distanceTraveledKm: 3.5,
    etaMinutes: 0.2,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: true,
    eventLog: '12:06:55 — Stable 3.0m hover established over customer pad.',
  },
  {
    id: 21,
    sceneNumber: 'PHASE 21',
    title: 'CONTROLLED PRECISION DESCENT',
    badge: 'Touchdown Descent',
    shortDesc: 'Descending smoothly at -0.4 m/s towards touchdown.',
    explanation: 'Descent rate monitored at -0.4 m/s. Proximity microswitches armed. Cargo winch unlocks.',
    duration: 4.0,
    cameraMode: 'follow',
    flightPhase: 'descent',
    status: 'delivery',
    dronePos: new THREE.Vector3(0, 1.8, 38),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 1.5,
    speed: 1,
    heading: 0,
    battery: 74,
    temperature: 34,
    signalRssi: 52,
    distanceTraveledKm: 3.5,
    etaMinutes: 0.1,
    payloadAttached: true,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: true,
    eventLog: '12:07:02 — Controlled descent to 1.5m AGL.',
  },
  {
    id: 22,
    sceneNumber: 'PHASE 22',
    title: 'PACKAGE DELIVERED & WINCH RELEASE',
    badge: 'Cargo Touchdown',
    shortDesc: 'Package safely touches down on customer pad; jaws release.',
    explanation: 'Automated cargo locker releases medical kit safely onto customer pad. Weight reduction detected; digital proof of delivery created.',
    duration: 4.5,
    cameraMode: 'operations',
    flightPhase: 'delivered',
    status: 'delivery',
    dronePos: new THREE.Vector3(0, 2.0, 38),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 2.0,
    speed: 0,
    heading: 0,
    battery: 74,
    temperature: 34,
    signalRssi: 52,
    distanceTraveledKm: 3.5,
    etaMinutes: 0.0,
    payloadAttached: false, // Cargo released!
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: true,
    decisionAlert: {
      type: 'info',
      title: 'CARGO SAFELY DELIVERED',
      details: 'ORD-10482 Delivered • Handover Proof: TXN-89201',
      reason: 'Zero impact damage, temperature maintained at 4°C.',
    },
    eventLog: '12:07:08 — Package ORD-10482 successfully delivered to customer pad.',
  },
  {
    id: 23,
    sceneNumber: 'PHASE 23',
    title: 'MISSION DELIVERY VERIFIED',
    badge: 'Ledger Confirmation',
    shortDesc: 'Delivery confirmed on SkyNav operations ledger & customer notified.',
    explanation: 'Delivery logged with zero safety incidents. Customer notified via SMS. Drone initiates pre-return clearance.',
    duration: 3.5,
    cameraMode: 'operations',
    flightPhase: 'delivered',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 3.5, 38),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 4.0,
    speed: 0,
    heading: 0,
    battery: 73,
    temperature: 33,
    signalRssi: 52,
    distanceTraveledKm: 3.5,
    etaMinutes: 0.0,
    payloadAttached: false,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: true,
    eventLog: '12:07:14 — Delivery phase marked 100% successful on SkyNav ledger.',
  },
  {
    id: 24,
    sceneNumber: 'PHASE 24',
    title: 'RETURN TO BASE (RTH) FLIGHT',
    badge: 'Autonomous Inbound',
    shortDesc: 'Drone turns 180°, ascends to 65m, and cruises home at 52 km/h.',
    explanation: 'Lightweight unloaded transit. Cruising along Inbound Corridor 4-Beta at 52 km/h back to Coimbatore Hub 01.',
    duration: 5.0,
    cameraMode: 'fpv',
    flightPhase: 'return',
    status: 'return',
    dronePos: new THREE.Vector3(0, 14, 0),
    droneRot: new THREE.Euler(0.12, Math.PI, 0),
    altitude: 65,
    speed: 52,
    heading: 180,
    battery: 69,
    temperature: 34,
    signalRssi: 58,
    distanceTraveledKm: 5.4,
    etaMinutes: 2.0,
    payloadAttached: false,
    obstacleScanning: true,
    isObstaclePresent: false,
    isRerouted: false,
    decisionAlert: {
      type: 'info',
      title: 'INBOUND TRANSIT ACTIVE',
      details: 'Destination: Coimbatore Hub Pad 1 (Inbound Corridor 4-Beta)',
      reason: 'Unloaded cruise efficiency: 96%.',
    },
    eventLog: '12:07:45 — Return to Base underway: Cruising at 52 km/h.',
  },
  {
    id: 25,
    sceneNumber: 'PHASE 25',
    title: 'HUB PAD PRECISION TOUCHDOWN',
    badge: 'Pad Touchdown',
    shortDesc: 'Precision touchdown on Coimbatore Hub Pad 1. Rotors brake.',
    explanation: 'Drone aligns and touches down on magnetic charging helipad. Motor ESCs brake and shut down.',
    duration: 4.5,
    cameraMode: 'hub',
    flightPhase: 'completed',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 66,
    temperature: 31,
    signalRssi: 64,
    distanceTraveledKm: 7.0,
    etaMinutes: 0.0,
    payloadAttached: false,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    eventLog: '12:08:15 — Touchdown on Hub Pad 1. Mission MIS-20491 complete.',
  },
  {
    id: 26,
    sceneNumber: 'PHASE 26',
    title: 'AUTOMATED CHARGING & AFTER-ACTION REPORT',
    badge: 'Mission Complete',
    shortDesc: 'Fast-charging contacts lock in; performance audit compiled (96/100).',
    explanation: '85 kW magnetic fast-charge dock engaged. After-Action Report and Mission Performance Score (96/100) generated with PDF export.',
    duration: 4.5,
    cameraMode: 'operations',
    flightPhase: 'completed',
    status: 'normal',
    dronePos: new THREE.Vector3(0, 0.2, -35),
    droneRot: new THREE.Euler(0, 0, 0),
    altitude: 0,
    speed: 0,
    heading: 0,
    battery: 66,
    temperature: 30,
    signalRssi: 64,
    distanceTraveledKm: 7.0,
    etaMinutes: 0.0,
    payloadAttached: false,
    obstacleScanning: false,
    isObstaclePresent: false,
    isRerouted: false,
    decisionAlert: {
      type: 'info',
      title: 'AFTER-ACTION REPORT GENERATED',
      details: 'Score: 96/100 • Total Time: 4m 32s • Safety: 100%',
      reason: 'Mission verified 100% compliant with DGCA regulations.',
    },
    eventLog: '12:08:20 — Fast-charge active. Mission Score: 96/100 compiled.',
  },
];

// Educational "How SkyNav Works" Guided Walkthrough (14 Scenes)
export const HOW_SKYNAV_WORKS_STORY = [
  {
    step: 1,
    title: 'Customer Submits Order',
    banner: 'STEP 1: ORDER DISPATCH',
    explanation: 'A customer or hospital orders emergency medicines via the SkyNav mobile app or API integration. Order ID and destination coordinates are generated.',
    targetScene: 1,
  },
  {
    step: 2,
    title: 'Admin Operations Control',
    banner: 'STEP 2: OPERATIONS OVERSIGHT',
    explanation: 'The SkyNav Central Command Center dashboard instantly ingests the order into the live operations queue, assigning safety priority tags.',
    targetScene: 2,
  },
  {
    step: 3,
    title: 'AI Mission Engine Planning',
    banner: 'STEP 3: 4D TRAJECTORY CALCULATION',
    explanation: 'The Mission Engine calculates the optimal 4D flight corridor, reserving airspace altitude bands and checking local weather and geofence restrictions.',
    targetScene: 3,
  },
  {
    step: 4,
    title: 'Multi-Factor Asset Evaluation',
    banner: 'STEP 4: FLEET SELECTION ALGORITHM',
    explanation: 'SkyNav ranks all available drones by battery percentage, payload capacity, maintenance history, and proximity to pick the ideal UAV.',
    targetScene: 5,
  },
  {
    step: 5,
    title: 'Autonomous Pre-Flight Diagnostics',
    banner: 'STEP 5: PRE-FLIGHT VERIFICATION',
    explanation: 'Before spinning rotors, the drone self-tests its dual RTK GPS locks, ESC motor currents, inertial sensors, battery cell health, and 5G command links.',
    targetScene: 6,
  },
  {
    step: 6,
    title: 'Automated Takeoff & Transition',
    banner: 'STEP 6: VERTICAL TAKEOFF',
    explanation: 'The drone executes vertical climb to clear ground obstacles, then smoothly transitions to horizontal cruise flight along the aerial corridor.',
    targetScene: 9,
  },
  {
    step: 7,
    title: 'Autonomous Cruise & Telemetry',
    banner: 'STEP 7: EN-ROUTE MONITORING',
    explanation: 'During flight, 50+ telemetry parameters stream to the cloud every second. The ground station monitors battery consumption curves and wind drift.',
    targetScene: 12,
  },
  {
    step: 8,
    title: 'LiDAR Obstacle Detection',
    banner: 'STEP 8: SENSOR SENSE & AVOID',
    explanation: 'Onboard LiDAR and computer vision sensors continuously scan the forward airspace for temporary obstacles, cranes, birds, or other aircraft.',
    targetScene: 14,
  },
  {
    step: 9,
    title: 'Autonomous Decision Engine',
    banner: 'STEP 9: DYNAMIC REROUTING',
    explanation: 'When an obstacle is detected, SkyNav AI automatically computes a lateral bypass vector within milliseconds without human intervention needed.',
    targetScene: 15,
  },
  {
    step: 10,
    title: 'Precision Destination Lock',
    banner: 'STEP 10: OPTICAL LANDING ZONE LOCK',
    explanation: 'Upon arriving at the destination, downward optical cameras lock onto the smart delivery pad visual fiducials for centimeter-level accuracy.',
    targetScene: 19,
  },
  {
    step: 11,
    title: 'Automated Tether Cargo Release',
    banner: 'STEP 11: SAFE PACKAGE RELEASE',
    explanation: 'The payload locker lowers the medical supplies securely to the ground while maintaining propeller clearance from trees and bystanders.',
    targetScene: 22,
  },
  {
    step: 12,
    title: 'Return to Base (RTH)',
    banner: 'STEP 12: RETURN TRANSIT',
    explanation: 'Having fulfilled the mission, the lightweight drone ascends to the return corridor and flies back to the logistics warehouse autonomously.',
    targetScene: 24,
  },
  {
    step: 13,
    title: 'Automated Hub Touchdown',
    banner: 'STEP 13: PAD LANDING & CHARGING',
    explanation: 'The drone lands precisely on the charging helipad and connects to automated magnetic fast-charging docks for the next flight.',
    targetScene: 25,
  },
  {
    step: 14,
    title: 'Post-Mission Analytics',
    banner: 'STEP 14: TELEMETRY LOGS & SCORE',
    explanation: 'A comprehensive flight audit report is compiled detailing flight efficiency, energy drain, route precision, and safety compliance score.',
    targetScene: 26,
  },
];

// Helper to generate dynamic multi-drone fleet configurations for 5, 10, 25, 50 drones
export const generateMultiDroneFleet = (count: number = 5): MultiDroneSimState[] => {
  const colors = ['#06b6d4', '#10b981', '#f59e0b', '#3b82f6', '#a855f7', '#ec4899', '#14b8a6', '#6366f1'];
  const fleet: MultiDroneSimState[] = [];

  for (let i = 1; i <= count; i++) {
    const idNum = i < 10 ? `0${i}` : `${i}`;
    const id = `D-${idNum}`;
    const color = colors[(i - 1) % colors.length];
    const angle = (i / count) * Math.PI * 2;
    const radius = 25 + (i % 3) * 5;

    const startX = Math.cos(angle) * radius;
    const startZ = Math.sin(angle) * radius;
    const targetX = -startX;
    const targetZ = -startZ;

    const altitude = 60 + (i % 4) * 20; // 60m, 80m, 100m, 120m
    const speed = 38 + (i % 5) * 3;
    const battery = 75 + ((i * 7) % 22);

    fleet.push({
      id,
      name: `SkyNav Airway Unit ${i}`,
      missionId: `MIS-10${300 + i}`,
      color,
      startPos: new THREE.Vector3(startX, 0.2, startZ),
      targetPos: new THREE.Vector3(targetX, 0.2, targetZ),
      currentPos: new THREE.Vector3(startX * 0.4, altitude * 0.2, startZ * 0.4),
      altitude,
      speed,
      battery,
      status: i % 4 === 0 ? 'Returning' : 'In Flight',
      progress: (i * 0.17) % 1.0,
    });
  }

  return fleet;
};

export const MULTI_DRONE_FLEET: MultiDroneSimState[] = generateMultiDroneFleet(5);
